name: libftTester

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macOS-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set $TERM & Test
        run:  |
                export TERM=xterm
                make actions
      - name: Upload output files
        uses: actions/upload-artifact@v3.1.0
        with:
          name: .o
          path: $(wildcard *.o)
          if-no-files-found: warn
          retention-days: 1
      - name: Upload output library
        uses: actions/upload-artifact@v3.1.0
        with:
          name: .a
          path: libft.a
          if-no-files-found: warn
          retention-days: 1

